### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kenshinaru** [ryzvision/prodia.js#6]
(node:39) UnhandledPromiseRejectionWarning: ReferenceError: fetch is not defined
2024-05-20T03:44:46.418672+00:00 app[worker.1]:     at sendRequest (/app/node_modules/prodia.js/dist/index.js:36:17)
2024-05-20T03:44:46.418673+00:00 app[worker.1]:     at generateImageSDXL (/app/node_modules/prodia.js/dist/index.js:98:28)

**Comment by UnschooledGamer** [comment]
Kindly give us additional information:
- npm package version of prodia.js you're using.
- Your NodeJs Version

**Comment by kenshinaru** [comment]
- npm prodia version = latest version(3.0.0)
- Nodejs 14.

**Comment by UnschooledGamer** [comment]
> * npm prodia version = latest version(3.0.0)
> * Nodejs 14.

Thanks for the information,
Please Update your NodeJs.

**Comment by kenshinaru** [comment]
is that all? ummm btw my error message shows that there is variable fetch is not defined in your prodia.ts sir, please check it

**Comment by flameface** [comment]
Install the LTS version of Node.js, as it includes node-fetch.

**Comment by kenshinaru** [comment]
okay thanks you sir, and thanks for making this package 🙏
